# Generated by Django 4.1.4 on 2022-12-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=50)),
                ('Con_Vida', models.BooleanField()),
                ('Hijos', models.IntegerField()),
            ],
        ),
    ]
